magic.Calendar=baidu.lang.createClass(function(a){this._options=baidu.object.extend({weekStart:"sun",initDate:baidu.i18n.date.toLocaleDate(new Date),highlightDates:[],disabledDates:[],disabledDayOfWeek:[],language:"zh-CN"},a||{});this.currentDate=new Date(this._options.initDate);this.selectedDate=new Date(this._options.initDate);this.dayNames=[]},{type:"magic.Calendar",superClass:magic.Base});
magic.Calendar.extend({tplSkeleton:'<div id="#{calendarId}" class="#{calendarClass}"><div id="#{titleId}" class="#{titleClass}"></div><div id="#{tableId}" class="#{tableClass}"></div></div>',tplDate:'<td id="#{id}" class="#{class}" onmouseover="#{mouseover}" onmouseout="#{mouseout}" onclick="#{click}">#{date}</td>',render:function(a){"string"===baidu.type(a)&&(a="#"+a);this.container=baidu(a)[0];this._renderSkeleton();this._renderTitle();this._renderDateTable();this._renderNavBtn();this._bindTable();
this._bindNavBtn();this._addkeystrokesListener();this.fire("render")},_rerender:function(){this._renderTitle();this._renderDateTable();this._bindTable()},_getId:function(a){return this._eid+(void 0===a?"tang_calendar":"tang_calendar_"+a)},_getClass:function(a){return void 0===a?"tang-calendar":"tang-calendar-"+a},_renderSkeleton:function(){baidu(this.container).insertHTML("beforeEnd",baidu.string.format(this.tplSkeleton,{calendarId:this._getId(),calendarClass:this._getClass(),titleId:this._getId("title"),
titleClass:this._getClass("title"),tableId:this._getId("table"),tableClass:this._getClass("table")}));this.titleEl=baidu("#"+this._getId("title"))[0];this.tableEl=baidu("#"+this._getId("table"))[0];this.$mappingDom("",baidu("#"+this._getId())[0]);this.$mappingDom("calendar",baidu("#"+this._getId())[0]);this.$mappingDom("title",this.titleEl);this.$mappingDom("table",this.tableEl)},_renderTitle:function(){var a=this.currentDate,b=a.getFullYear(),a=a.getMonth()+1;this.titleEl.innerHTML=baidu.string.format(baidu.i18n.cultures[this._options.language].calendar.titleNames,
{yyyy:b,MM:baidu.i18n.cultures[this._options.language].calendar.monthNamesShort[a-1]})},_renderDateTable:function(){var a=this._getTheadString(),b=this._getTbodyString();this.tableEl.innerHTML='<table border="0" cellpadding="0" cellspacing="0">'+a+b+"</table>"},_renderNavBtn:function(){var a=baidu("#"+this._getId())[0],b=document,c=b.createElement("div"),e=b.createElement("div"),d=b.createElement("div"),b=b.createElement("div");c.className=this._getClass("prebtn");e.className=this._getClass("nextbtn");
d.className=this._getClass("yprebtn");b.className=this._getClass("ynextbtn");a.appendChild(c);a.appendChild(e);a.appendChild(d);a.appendChild(b);this.preBtn=c;this.nextBtn=e;this.ypreBtn=d;this.ynextBtn=b;this.$mappingDom("premonthbtn",c);this.$mappingDom("nextmonthbtn",e);this.$mappingDom("preyearbtn",d);this.$mappingDom("preyearhbtn",b)},_bindNavBtn:function(){var a=this,b=a.preBtn,c=a.nextBtn,e=a.ypreBtn,d=a.ynextBtn,f=!1,h,g,l,m,n,p,q,r,s;baidu(b).on("click",h=function(){!f&&a.preMonth();f=!1;
a.fire("premonth")});baidu(c).on("click",g=function(){!f&&a.nextMonth();f=!1;a.fire("nextmonth")});baidu(e).on("click",l=function(){!f&&a.preYear();f=!1;a.fire("preyear")});baidu(d).on("click",m=function(){!f&&a.nextYear();f=!1;a.fire("nextyear")});var j=null,k=function(b,c){function d(){j=setTimeout(function(){c?"pre"==b?a.preYear():a.nextYear():"pre"==b?a.preMonth():a.nextMonth();f=!0;d()},500)}j||d()};baidu(b).on("mousedown",n=function(){k("pre")});baidu(c).on("mousedown",p=function(){k("next")});
baidu(e).on("mousedown",q=function(){k("pre",!0)});baidu(d).on("mousedown",r=function(){k("next",!0)});baidu(document).on("mouseup",s=function(){!a.disposed&&j&&(clearTimeout(j),j=null)});a.on("dispose",function(){baidu(b).off("click",h);baidu(c).off("click",g);baidu(e).off("click",l);baidu(d).off("click",m);baidu(b).off("mousedown",n);baidu(c).off("mousedown",p);baidu(e).off("mousedown",q);baidu(d).off("mousedown",r);baidu(document).off("mouseup",s)})},_getTheadString:function(){var a="mon tue wed thu fri sat sun".split(" "),
b,c=[];b=this._options.weekStart.toLowerCase();var e=baidu.array.indexOf(a,b),d=baidu.i18n.cultures[this._options.language].calendar.dayNames,f=0;for(c.push('<thead class="'+this._getClass("weekdays")+'"><tr>');7>f;f++)6<e&&(e=0),this.dayNames.push(a[e]),b=d[a[e]],c.push("<th>"+b+"</th>"),e++;c.push("</tr></thead>");return c.join("")},_getTbodyString:function(){var a=this.dayNames,b=new Date(this.currentDate),c;c=0;var e=[],d=baidu.i18n.date.getDaysInMonth(b.getFullYear(),b.getMonth()),f=5,h=c="";
b.setDate(1);c=b.getDay();c=baidu.array.indexOf(a,"sun mon tue wed thu fri sat".split(" ")[c]);35<c+d&&(f=6);b.setDate(b.getDate()-c);for(var d=a=0,g="";a<f;a++){for(e.push("<tr>");7>d;d++){g=this._getClass("date");c="";if(0==b.getDay()||6==b.getDay())g+=" "+this._getClass("weekend");this._datesEqual(baidu.i18n.date.toLocaleDate(new Date),b)&&(g+=" "+this._getClass("today"));this._datesContains(this._options.highlightDates,b)&&(g+=" "+this._getClass("highlight"));this._datesContains(this._options.disabledDates,
b)&&(g+=" "+this._getClass("disable"));this._dayOfWeekInDisabled(b.getDay())&&(g+=" "+this._getClass("disable"));this._datesEqual(this.selectedDate,b)&&(g+=" "+this._getClass("selected"),c='id="'+this._getId("selected")+'"');if(b.getMonth()<this.currentDate.getMonth()||b.getFullYear()<this.currentDate.getFullYear())g+=" "+this._getClass("premonth");else if(b.getMonth()>this.currentDate.getMonth()||b.getFullYear()>this.currentDate.getFullYear())g+=" "+this._getClass("nextmonth");h=this._formatDate(new Date(b.getFullYear()+
"/"+(b.getMonth()+1)+"/"+b.getDate()));e.push("<td "+c+' class="'+g+'" date="'+h+'" onmouseover=baiduInstance("'+this.guid+'")._mouseoverHandler(event) onmouseout=baiduInstance("'+this.guid+'")._mouseoutHandler(event)>'+b.getDate()+"</td>");b.setDate(b.getDate()+1)}e.push("</tr>");d=0}return"<tbody>"+e.join("")+"</tbody>"},_formatDate:function(a){var b=a.getFullYear(),c=a.getMonth()+1;a=a.getDate();return b+"/"+(10<=c?c:"0"+c)+"/"+(10<=a?a:"0"+a)},_mouseoverHandler:function(a){a=baidu.event(a).target;
baidu(a).addClass(this._getClass("hover"));this.fire("mouseover",{target:a})},_mouseoutHandler:function(a){a=baidu.event(a).target;baidu(a).removeClass(this._getClass("hover"));this.fire("mouseout",{target:a})},_bindTable:function(){var a=this,b=baidu("#"+a._getId("table"))[0].getElementsByTagName("tbody")[0],c,e,d,f,h;baidu(b).on("click",h=function(b){c=b.target;if("TD"==c.tagName.toUpperCase()&&(e=c.getAttribute("date"),d=new Date(e),b=a.selectedDate,d.setHours(b.getHours()),d.setMinutes(b.getMinutes()),
d.setSeconds(b.getSeconds()),!a._datesContains(a._options.disabledDates,d)&&!a._dayOfWeekInDisabled(d.getDay()))){if(f=baidu("#"+a._getId("selected"))[0])f.id="",baidu(f).removeClass(a._getClass("selected"));c.id=a._getId("selected");baidu(c).addClass(a._getClass("selected"));e=a._formatDate(d);a.selectedDate=new Date(e);a.fire("selectdate",{date:new Date(e)})}});a.on("dispose",function(){baidu(b).off("click",h)})},_addkeystrokesListener:function(){function a(a){a=a||window.event;var c=!0;switch(a.keyCode){case 33:b.preMonth();
break;case 34:b.nextMonth();break;case 37:b._preDay();break;case 38:b._preDay();break;case 39:b._nextDay();break;case 40:b._nextDay();break;default:c=!1}c&&a.preventDefault()}var b=this,c=!1,e=baidu("#"+b._getId())[0],d;baidu(document).on("click",d=function(d){b.disposed||(d=d.target,baidu.dom.contains(e,d)||d==e?c||(baidu(document).on("keydown",a),c=!0):(baidu(document).off("keydown",a),c=!1))});b.on("dispose",function(){baidu(document).off("click",d)})},_datesEqual:function(a,b){if(!("date"!=baidu.type(a)||
"date"!=baidu.type(b))){var c=a.getFullYear(),e=a.getMonth(),d=a.getDate(),f=b.getFullYear(),h=b.getMonth(),g=b.getDate();return c==f&&e==h&&d==g}},_days:{mon:1,tue:2,wed:3,thu:4,fri:5,sat:6,sun:0},_dayOfWeekInDisabled:function(a){for(var b=this._options.disabledDayOfWeek,c=this._days,e=!1,d=0,f;d<b.length&&!(f=b[d],"object"==typeof f?(c[f.start]||0)<=a&&a<=c[f.end]&&(e=!0):c[f]==a&&(e=!0),e);d++);return e},_datesContains:function(a,b){var c=0,e=a.length,d;if("date"==baidu.type(b)){for(;c<e;c++)if(d=
a[c],baidu.lang.isDate(d)){if(this._datesEqual(d,b))return!0}else if(d.end&&(d.end=new Date(baidu.date.format(d.end,"yyyy/MM/dd")+" 23:59:59")),(!d.start||b.getTime()>=d.start.getTime())&&(!d.end||b.getTime()<=d.end.getTime()))return!0;return!1}},go:function(a,b){this.currentDate.setFullYear(a);this.currentDate.setDate(1);b=void 0===b?this.currentDate.getMonth():b-1;this.currentDate.setMonth(b);this._rerender()},getDate:function(){return new Date(this.selectedDate)},setDate:function(a){var b=new Date(a);
if("date"!=baidu.type(a))return!1;if(!this._datesContains(this._options.disabledDates,b)&&!this._dayOfWeekInDisabled(b.getDay()))return this.currentDate=new Date(a),this.selectedDate=new Date(a),this._rerender(),!0},preMonth:function(){var a=this.currentDate,b=a.getMonth()+1,a=a.getFullYear();this.go(a,b-1)},nextMonth:function(){var a=this.currentDate,b=a.getMonth()+1,a=a.getFullYear();this.go(a,b+1)},preYear:function(){var a=this.currentDate;this.go(a.getFullYear()-1,a.getMonth()+1)},nextYear:function(){var a=
this.currentDate;this.go(a.getFullYear()+1,a.getMonth()+1)},_preDay:function(){var a=new Date(this.selectedDate);a.setDate(a.getDate()-1);this.setDate(a);this.fire("selectdate",{date:a})},_nextDay:function(){var a=new Date(this.selectedDate);a.setDate(a.getDate()+1);this.setDate(a);this.fire("selectdate",{date:a})},$dispose:function(){this.disposed||(this.container.removeChild(baidu("#"+this._getId())[0]),magic.Base.prototype.$dispose.call(this))}});
